// Lista anual de datas comemorativas (base gastronomia) para o quick-add do Cronograma.
// A social media marca as que quer e elas viram itens em cronograma_datas.

export type DataComemorativaItem = { label: string; day: string };
export type DataComemorativaGroup = { month: string; items: DataComemorativaItem[] };

export const DATAS_COMEMORATIVAS: DataComemorativaGroup[] = [
  { month: "Abril", items: [
    { label: "Dia Mundial da Saúde", day: "07/04" },
    { label: "Dia do Fondue de Queijo", day: "11/04" },
    { label: "Dia Mundial do Café", day: "14/04" },
    { label: "Páscoa", day: "data móvel" },
    { label: "Sexta-feira Santa", day: "data móvel" },
    { label: "Tiradentes", day: "21/04" },
    { label: "Dia da Mandioca", day: "22/04" },
    { label: "Dia do Livro", day: "23/04" },
    { label: "Dia do Churrasco", day: "24/04" },
  ] },
  { month: "Maio", items: [
    { label: "Dia do Trabalhador", day: "01/05" },
    { label: "Dia Mundial do Atum", day: "02/05" },
    { label: "Dia da Cozinheira", day: "10/05" },
    { label: "Dia das Mães", day: "2º domingo" },
    { label: "Dia Nacional do Chefe de Cozinha", day: "13/05" },
    { label: "Dia Mundial do Whisky", day: "3º sábado" },
    { label: "Dia Internacional do Chá", day: "21/05" },
    { label: "Dia Internacional do Hambúrguer", day: "28/05" },
    { label: "Dia Mundial da Batata Frita", day: "30/05" },
  ] },
  { month: "Junho", items: [
    { label: "Dia Mundial do Meio Ambiente", day: "05/06" },
    { label: "Dia dos Namorados", day: "12/06" },
    { label: "Festas Juninas", day: "mês inteiro" },
    { label: "Dia da Gastronomia Sustentável", day: "18/06" },
    { label: "Corpus Christi", day: "data móvel" },
  ] },
  { month: "Julho", items: [
    { label: "Férias escolares", day: "período" },
    { label: "Dia da Gastronomia Mineira", day: "06/07" },
    { label: "Dia Mundial do Chocolate", day: "07/07" },
    { label: "Dia do Panificador", day: "08/07" },
    { label: "Dia da Pizza", day: "10/07" },
    { label: "Dia do Rock", day: "13/07" },
    { label: "Dia Internacional da Tequila", day: "24/07" },
    { label: "Dia da Lasanha", day: "29/07" },
  ] },
  { month: "Agosto", items: [
    { label: "Dia Internacional da Cerveja", day: "1ª sexta" },
    { label: "Dia Mundial da Ostra", day: "05/08" },
    { label: "Dia Nacional do Vinho", day: "07/08" },
    { label: "Dia do Garçom", day: "11/08" },
    { label: "Dia dos Pais", day: "2º domingo" },
    { label: "Dia do Pão de Queijo", day: "17/08" },
    { label: "Dia da Pimenta-do-Reino", day: "29/08" },
    { label: "Dia do Bacon", day: "31/08" },
    { label: "Dia da Nutricionista", day: "31/08" },
  ] },
  { month: "Setembro", items: [
    { label: "Independência do Brasil", day: "07/09" },
    { label: "Dia do Cachorro-Quente", day: "09/09" },
    { label: "Dia Nacional da Esfirra", day: "09/09" },
    { label: "Dia do Milk Shake", day: "10/09" },
    { label: "Dia Nacional da Cachaça", day: "13/09" },
    { label: "Dia do Cliente", day: "15/09" },
    { label: "Início da Primavera", day: "data móvel" },
    { label: "Dia da Banana", day: "22/09" },
    { label: "Dia do Sorvete", day: "23/09" },
    { label: "Dia Mundial do Turismo", day: "27/09" },
  ] },
  { month: "Outubro", items: [
    { label: "Dia Mundial do Vegetarianismo", day: "01/10" },
    { label: "Dia do Barman", day: "04/10" },
    { label: "Dia da Sobremesa", day: "09/10" },
    { label: "Dia Mundial do Ovo", day: "2ª sexta" },
    { label: "Dia das Crianças", day: "12/10" },
    { label: "Nossa Senhora Aparecida", day: "12/10" },
    { label: "Dia do Chef de Cozinha", day: "13/10" },
    { label: "Dia Mundial da Alimentação", day: "16/10" },
    { label: "Dia Mundial do Pão", day: "16/10" },
    { label: "Dia Internacional do Nacho", day: "21/10" },
    { label: "Dia Mundial do Macarrão", day: "25/10" },
    { label: "Dia Mundial do Cheesecake", day: "25/10" },
    { label: "Halloween", day: "31/10" },
  ] },
  { month: "Novembro", items: [
    { label: "Dia do Sushi", day: "01/11" },
    { label: "Dia Mundial do Veganismo", day: "01/11" },
    { label: "Finados", day: "02/11" },
    { label: "Dia do Sanduíche", day: "03/11" },
    { label: "Dia do Trigo", day: "10/11" },
    { label: "Proclamação da República", day: "15/11" },
    { label: "Dia Nacional da Consciência Negra", day: "20/11" },
    { label: "Black Friday", day: "última sexta" },
  ] },
  { month: "Dezembro", items: [
    { label: "Dia Nacional do Samba", day: "02/12" },
    { label: "Dia da Família", day: "08/12" },
    { label: "Dia do Profissional de Culinária", day: "09/12" },
    { label: "Confraternizações de fim de ano", day: "período" },
    { label: "Início do inverno", day: "21/12" },
    { label: "Natal", day: "25/12" },
    { label: "Réveillon", day: "31/12" },
  ] },
];
